#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#########################################################################
# Author: Zhaoting Weng
# Created Time: Wed 30 May 2018 05:34:07 PM CST
# Description:
#########################################################################

import argparse

def NewUml(path):
    with open(path, 'w') as f:
        f.write('''@startuml
title Awesome Title

actor FrontEnd
participant API
participant Access
database MgrDB

@enduml''')



if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('filename')
    args = parser.parse_args()
    NewUml(args.filename+'.uml')

